### ISSUE TITLE
Problems with Evaluations

### ISSUE THREAD

**Issue by jmiemirza** [asharakeh/kitti_native_evaluation#7]
Hi,

I have been using a new dataset but it has been built on the same format as KITTI. I am having trouble with the evaluation script. When I run the evaluation script to evaluate all the checkpoints, nothing is written in the results file. I am attaching a screenshot:
![image](https://user-images.githubusercontent.com/50660423/78043537-c282b280-7373-11ea-994a-2df8697fe83b.png)

This is how it looks. However, I tried with just 50 samples of the same dataset and it provided me with the following output file:

![image](https://user-images.githubusercontent.com/50660423/78043585-d3332880-7373-11ea-9ca5-b07c7d3a0869.png)

Now when I follow the readme and evaluate individual checkpoints, I get only the Car Detection AP and then a segmentation fault. 

Did anyone have the same problem?

Thanks

**Comment by asharakeh** [comment]
@jmiemirza this might be caused by multiple issues. I would recommend the following:

1. Check if your results are written appropriatly. 
2. Check if you have a score value per result at the 16th column and that the score is between 0-1. 
3. Check if your bounding boxes make sense. 2D bounding boxes should never be negative, 3D bounding boxes should have positive z coordinate etc...
